services:
  - type: web
    name: bot-wa-nextjs
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_BASE_URL
        value: https://bot-wa-nextjs.onrender.com # Change this to your actual Render URL
